-- Modern JavaScript Placement Test Questions
-- Comprehensive test covering ES6+, modern patterns, and best practices

-- Clear existing questions first (if any)
DELETE FROM public.placement_questions;

-- Insert modern JavaScript questions
INSERT INTO public.placement_questions (question, options, correct_answer, difficulty_level, points, explanation, topic) VALUES

-- BEGINNER LEVEL (Modern JS Fundamentals)
('¿Cuál es la diferencia principal entre let y var?', 
 '["let tiene scope de función, var tiene scope de bloque", "let tiene scope de bloque, var tiene scope de función", "No hay diferencia", "let es más lento que var"]', 
 'let tiene scope de bloque, var tiene scope de función', 
 'beginner', 
 1, 
 'let introduce block scope, mientras que var tiene function scope, evitando muchos problemas comunes.',
 'variables'),

('¿Cómo se declara una función arrow en JavaScript?', 
 '["const func = () => {}", "function func() => {}", "const func => () {}", "func => () => {}"]', 
 'const func = () => {}', 
 'beginner', 
 1, 
 'Las arrow functions se declaran con la sintaxis const nombre = () => {}.',
 'functions'),

('¿Qué hace el operador de destructuring en este código: const {name, age} = person?', 
 '["Crea un objeto", "Extrae propiedades del objeto person", "Elimina propiedades", "Compara objetos"]', 
 'Extrae propiedades del objeto person', 
 'beginner', 
 1, 
 'Destructuring permite extraer propiedades de objetos o elementos de arrays de forma concisa.',
 'objects'),

('¿Cuál es el resultado de `Hello ${name}` donde name = "World"?', 
 '["Hello ${name}", "Hello World", "Hello name", "Error"]', 
 'Hello World', 
 'beginner', 
 1, 
 'Template literals (backticks) permiten interpolación de variables con ${}.',
 'template-literals'),

('¿Qué hace const en JavaScript?', 
 '["Crea una variable que nunca cambia", "Crea una variable inmutable", "Previene la reasignación de la variable", "Es igual que var"]', 
 'Previene la reasignación de la variable', 
 'beginner', 
 1, 
 'const previene la reasignación, pero el contenido de objetos/arrays puede mutar.',
 'variables'),

('¿Cómo se importa una función por defecto en ES6 modules?', 
 '["import {func} from \"./module\"", "import func from \"./module\"", "import * as func from \"./module\"", "require(\"./module\")"]', 
 'import func from "./module"', 
 'beginner', 
 1, 
 'Las exportaciones por defecto se importan sin llaves: import nombre from "ruta".',
 'es6-modules'),

('¿Cuál es la forma moderna de crear un string multilínea?', 
 '["\"línea1\" + \"\\n\" + \"línea2\"", "`línea1\nlínea2`", "\"línea1\\nlínea2\"", "String.multiline(\"línea1\", \"línea2\")"]', 
 '`línea1\nlínea2`', 
 'beginner', 
 1, 
 'Template literals permiten strings multilínea de forma natural sin concatenación.',
 'template-literals'),

('¿Cuál es la diferencia entre == y === en JavaScript?', 
 '["No hay diferencia", "== compara valor, === compara valor y tipo", "=== es más rápido", "== es para números, === para strings"]', 
 '== compara valor, === compara valor y tipo', 
 'beginner', 
 1, 
 '== realiza coerción de tipos, mientras que === compara valor y tipo sin coerción.',
 'variables'),

('¿Qué devuelve typeof null en JavaScript?', 
 '["null", "undefined", "object", "error"]', 
 'object', 
 'beginner', 
 1, 
 'Es un bug histórico de JavaScript que typeof null devuelve "object".',
 'variables'),

('¿Cuál es el resultado de [1, 2, 3].map(x => x * 2)?', 
 '["[1, 2, 3]", "[2, 4, 6]", "6", "error"]', 
 '[2, 4, 6]', 
 'beginner', 
 1, 
 'map() crea un nuevo array aplicando la función a cada elemento.',
 'arrays'),

('¿Qué es el "hoisting" en JavaScript?', 
 '["Un error de sintaxis", "El proceso de elevar declaraciones al inicio del scope", "Una función built-in", "Un tipo de loop"]', 
 'El proceso de elevar declaraciones al inicio del scope', 
 'beginner', 
 1, 
 'Hoisting es el comportamiento de JavaScript de mover declaraciones al inicio de su scope.',
 'variables'),

-- INTERMEDIATE LEVEL (Advanced ES6+, Async, Modern Patterns)
('¿Qué devuelve una función async que no tiene return explícito?', 
 '["undefined", "null", "Promise<undefined>", "Error"]', 
 'Promise<undefined>', 
 'intermediate', 
 2, 
 'Las funciones async siempre devuelven una Promise, incluso sin return explícito.',
 'async-await'),

('¿Cuál es la diferencia entre Promise.all() y Promise.allSettled()?', 
 '["No hay diferencia", "all() se rechaza si una falla, allSettled() espera todas", "allSettled() es más rápido", "all() maneja errores mejor"]', 
 'all() se rechaza si una falla, allSettled() espera todas', 
 'intermediate', 
 2, 
 'Promise.all falla rápido, Promise.allSettled espera todas las promesas sin importar el resultado.',
 'promises'),

('¿Qué hace el operador nullish coalescing (??) en JavaScript?', 
 '["Igual que ||", "Devuelve el lado derecho solo si el izquierdo es null o undefined", "Compara valores", "Es un operador ternario"]', 
 'Devuelve el lado derecho solo si el izquierdo es null o undefined', 
 'intermediate', 
 2, 
 'El operador ?? solo considera null y undefined como falsy, no otros valores como 0 o "".',
 'variables'),

('¿Cuál es el resultado de [...[1, 2], ...[3, 4]]?', 
 '["[1, 2, 3, 4]", "[[1, 2], [3, 4]]", "[1, 2], [3, 4]", "Error"]', 
 '[1, 2, 3, 4]', 
 'intermediate', 
 2, 
 'El spread operator (...) expande arrays, combinándolos en uno solo.',
 'arrays'),

('¿Qué es optional chaining (?.) en JavaScript?', 
 '["Un operador para arrays", "Permite acceder a propiedades sin error si son undefined", "Un tipo de loop", "Una función built-in"]', 
 'Permite acceder a propiedades sin error si son undefined', 
 'intermediate', 
 2, 
 'Optional chaining (?.) permite acceder a propiedades anidadas sin errores si algún nivel es null/undefined.',
 'objects'),

('¿Cuál es la diferencia entre map() y forEach()?', 
 '["No hay diferencia", "map() devuelve un nuevo array, forEach() no", "forEach() es más rápido", "map() modifica el array original"]', 
 'map() devuelve un nuevo array, forEach() no', 
 'intermediate', 
 2, 
 'map() transforma elementos y devuelve un nuevo array, forEach() solo itera sin retornar.',
 'array-methods'),

('¿Qué hace Object.freeze()?', 
 '["Congela el navegador", "Hace un objeto inmutable superficialmente", "Elimina un objeto", "Copia un objeto"]', 
 'Hace un objeto inmutable superficialmente', 
 'intermediate', 
 2, 
 'Object.freeze() previene modificaciones a las propiedades del primer nivel del objeto.',
 'objects'),

('¿Cuál es la diferencia entre for...in y for...of?', 
 '["No hay diferencia", "for...in itera índices/claves, for...of itera valores", "for...of es más lento", "for...in es para objetos, for...of para arrays"]', 
 'for...in itera índices/claves, for...of itera valores', 
 'intermediate', 
 2, 
 'for...in itera propiedades enumerables, for...of itera valores de iterables.',
 'arrays'),

-- INTERMEDIATE LEVEL (Additional concepts for intermediate users)

('¿Cuál es el resultado de [1, 2, 3].filter(x => x > 1)?', 
 '["[1, 2, 3]", "[2, 3]", "[1]", "error"]', 
 '[2, 3]', 
 'intermediate', 
 2, 
 'filter() crea un nuevo array con elementos que pasan la condición.',
 'array-methods'),

('¿Cuál es la diferencia entre call() y apply()?', 
 '["No hay diferencia", "call() acepta argumentos individuales, apply() acepta un array", "apply() es más rápido", "call() es para objetos, apply() para arrays"]', 
 'call() acepta argumentos individuales, apply() acepta un array', 
 'intermediate', 
 2, 
 'call() pasa argumentos individualmente, apply() los pasa como array.',
 'functions'),

('¿Qué es una closure en JavaScript?', 
 '["Un tipo de loop", "Una función que tiene acceso a variables de su scope externo", "Un método de array", "Un operador"]', 
 'Una función que tiene acceso a variables de su scope externo', 
 'intermediate', 
 2, 
 'Una closure permite que una función acceda a variables de su scope léxico externo.',
 'closures'),

('¿Cuál es el resultado de 0.1 + 0.2 === 0.3 en JavaScript?', 
 '["true", "false", "undefined", "error"]', 
 'false', 
 'intermediate', 
 2, 
 'Debido a la precisión de punto flotante, 0.1 + 0.2 no es exactamente 0.3.',
 'variables'),

('¿Qué hace el operador spread (...) con objetos?', 
 '["Los elimina", "Crea una copia superficial", "Los convierte en array", "Causa un error"]', 
 'Crea una copia superficial', 
 'intermediate', 
 2, 
 'El operador spread crea una copia superficial de las propiedades del objeto.',
 'objects'),

('¿Cuál es la diferencia entre JSON.stringify() y JSON.parse()?', 
 '["No hay diferencia", "stringify convierte a string, parse convierte de string", "parse es más rápido", "stringify es para objetos, parse para arrays"]', 
 'stringify convierte a string, parse convierte de string', 
 'intermediate', 
 2, 
 'JSON.stringify() serializa objetos a JSON string, JSON.parse() deserializa JSON string a objetos.',
 'objects'),

('¿Qué hace el método Array.reduce()?', 
 '["Reduce el tamaño del array", "Combina todos los elementos en un solo valor", "Elimina elementos", "Ordena el array"]', 
 'Combina todos los elementos en un solo valor', 
 'intermediate', 
 2, 
 'reduce() ejecuta una función reductora en cada elemento del array, resultando en un solo valor.',
 'array-methods');
